In [1]:
import numpy as np

In [2]:
import pandas as pd

In [5]:
pd.read_csv('pandas_tutorial_read.csv', delimiter =';')

      2018-01-01 00:01:01  read  country_7  2458151261      SEO  North America
0     2018-01-01 00:03:20  read  country_7  2458151262      SEO  South America
1     2018-01-01 00:04:01  read  country_7  2458151263  AdWords         Africa
2     2018-01-01 00:04:02  read  country_7  2458151264  AdWords         Europe
3     2018-01-01 00:05:03  read  country_8  2458151265   Reddit  North America
4     2018-01-01 00:05:42  read  country_6  2458151266   Reddit  North America
5     2018-01-01 00:06:06  read  country_2  2458151267   Reddit         Europe
6     2018-01-01 00:06:15  read  country_6  2458151268  AdWords         Europe
7     2018-01-01 00:07:21  read  country_7  2458151269  AdWords  North America
8     2018-01-01 00:07:29  read  country_5  2458151270   Reddit  North America
9     2018-01-01 00:07:57  read  country_5  2458151271  AdWords           Asia
10    2018-01-01 00:08:57  read  country_7  2458151272      SEO      Australia
11    2018-01-01 00:09:11  read  country_5  2458151273   Reddit           Asia
12    2018-01-01 00:09:29  read  country_2  2458151274   Reddit         Europe
13    2018-01-01 00:11:06  read  country_7  2458151275   Reddit         Africa
14    2018-01-01 00:11:22  read  country_7  2458151276      SEO  North America
15    2018-01-01 00:13:05  read  country_8  2458151277      SEO  North America
16    2018-01-01 00:13:06  read  country_2  2458151278   Reddit           Asia
17    2018-01-01 00:13:39  read  country_4  2458151279      SEO  North America
18    2018-01-01 00:14:53  read  country_2  2458151280   Reddit           Asia
19    2018-01-01 00:15:44  read  country_2  2458151281   Reddit           Asia
20    2018-01-01 00:15:50  read  country_7  2458151282   Reddit         Africa
21    2018-01-01 00:17:15  read  country_2  2458151283  AdWords         Europe
22    2018-01-01 00:17:31  read  country_2  2458151284   Reddit           Asia
23    2018-01-01 00:17:58  read  country_7  2458151285   Reddit         Africa
24    2018-01-01 00:18:55  read  country_2  2458151286  AdWords  North America
25    2018-01-01 00:20:18  read  country_5  2458151287      SEO  North America
26    2018-01-01 00:20:44  read  country_2  2458151288      SEO  North America
27    2018-01-01 00:23:16  read  country_2  2458151289   Reddit           Asia
28    2018-01-01 00:23:51  read  country_7  2458151290   Reddit           Asia
29    2018-01-01 00:24:52  read  country_6  2458151291      SEO  North America
...                   ...   ...        ...         ...      ...            ...
1764  2018-01-01 23:41:11  read  country_2  2458153026   Reddit         Africa
1765  2018-01-01 23:41:51  read  country_5  2458153027  AdWords           Asia
1766  2018-01-01 23:43:54  read  country_5  2458153028  AdWords         Europe
1767  2018-01-01 23:44:52  read  country_8  2458153029   Reddit  South America
1768  2018-01-01 23:45:09  read  country_5  2458153030  AdWords      Australia
1769  2018-01-01 23:45:12  read  country_6  2458153031   Reddit           Asia
1770  2018-01-01 23:45:56  read  country_5  2458153032  AdWords         Africa
1771  2018-01-01 23:45:58  read  country_7  2458153033      SEO  South America
1772  2018-01-01 23:46:13  read  country_8  2458153034   Reddit           Asia
1773  2018-01-01 23:46:22  read  country_2  2458153035  AdWords           Asia
1774  2018-01-01 23:47:19  read  country_2  2458153036  AdWords           Asia
1775  2018-01-01 23:49:04  read  country_6  2458153037   Reddit           Asia
1776  2018-01-01 23:49:52  read  country_5  2458153038      SEO  North America
1777  2018-01-01 23:51:17  read  country_2  2458153039   Reddit           Asia
1778  2018-01-01 23:51:25  read  country_4  2458153040      SEO  South America
1779  2018-01-01 23:51:46  read  country_8  2458153041  AdWords         Africa
1780  2018-01-01 23:51:52  read  country_2  2458153042   Reddit           Asia
1781  2018-01-01 23:53:03  read  country_2  2458153043  AdWords           Asia
1782  2018-01-01 23:53:33  read  country_3  2458153044   Reddit           Asia
1783  2018-01-01 23:54:03  read  country_2  2458153045      SEO  North America
1784  2018-01-01 23:54:26  read  country_2  2458153046  AdWords         Africa
1785  2018-01-01 23:54:39  read  country_6  2458153047   Reddit           Asia
1786  2018-01-01 23:54:45  read  country_2  2458153048   Reddit           Asia
1787  2018-01-01 23:55:04  read  country_7  2458153049  AdWords         Europe
1788  2018-01-01 23:56:42  read  country_4  2458153050  AdWords           Asia
1789  2018-01-01 23:57:14  read  country_2  2458153051  AdWords  North America
1790  2018-01-01 23:58:33  read  country_8  2458153052      SEO           Asia
1791  2018-01-01 23:59:36  read  country_6  2458153053   Reddit           Asia
1792  2018-01-01 23:59:36  read  country_7  2458153054  AdWords         Europe
1793  2018-01-01 23:59:38  read  country_5  2458153055   Reddit           Asia

[1794 rows x 6 columns]

In [7]:
article_read = pd.read_csv('pandas_tutorial_read.csv', delimiter=';', names = ['my_datetime', 'event', 'country', 'user_id', 'source', 'topic'])

In [8]:
article_read

              my_datetime event    country     user_id   source          topic
0     2018-01-01 00:01:01  read  country_7  2458151261      SEO  North America
1     2018-01-01 00:03:20  read  country_7  2458151262      SEO  South America
2     2018-01-01 00:04:01  read  country_7  2458151263  AdWords         Africa
3     2018-01-01 00:04:02  read  country_7  2458151264  AdWords         Europe
4     2018-01-01 00:05:03  read  country_8  2458151265   Reddit  North America
5     2018-01-01 00:05:42  read  country_6  2458151266   Reddit  North America
6     2018-01-01 00:06:06  read  country_2  2458151267   Reddit         Europe
7     2018-01-01 00:06:15  read  country_6  2458151268  AdWords         Europe
8     2018-01-01 00:07:21  read  country_7  2458151269  AdWords  North America
9     2018-01-01 00:07:29  read  country_5  2458151270   Reddit  North America
10    2018-01-01 00:07:57  read  country_5  2458151271  AdWords           Asia
11    2018-01-01 00:08:57  read  country_7  2458151272      SEO      Australia
12    2018-01-01 00:09:11  read  country_5  2458151273   Reddit           Asia
13    2018-01-01 00:09:29  read  country_2  2458151274   Reddit         Europe
14    2018-01-01 00:11:06  read  country_7  2458151275   Reddit         Africa
15    2018-01-01 00:11:22  read  country_7  2458151276      SEO  North America
16    2018-01-01 00:13:05  read  country_8  2458151277      SEO  North America
17    2018-01-01 00:13:06  read  country_2  2458151278   Reddit           Asia
18    2018-01-01 00:13:39  read  country_4  2458151279      SEO  North America
19    2018-01-01 00:14:53  read  country_2  2458151280   Reddit           Asia
20    2018-01-01 00:15:44  read  country_2  2458151281   Reddit           Asia
21    2018-01-01 00:15:50  read  country_7  2458151282   Reddit         Africa
22    2018-01-01 00:17:15  read  country_2  2458151283  AdWords         Europe
23    2018-01-01 00:17:31  read  country_2  2458151284   Reddit           Asia
24    2018-01-01 00:17:58  read  country_7  2458151285   Reddit         Africa
25    2018-01-01 00:18:55  read  country_2  2458151286  AdWords  North America
26    2018-01-01 00:20:18  read  country_5  2458151287      SEO  North America
27    2018-01-01 00:20:44  read  country_2  2458151288      SEO  North America
28    2018-01-01 00:23:16  read  country_2  2458151289   Reddit           Asia
29    2018-01-01 00:23:51  read  country_7  2458151290   Reddit           Asia
...                   ...   ...        ...         ...      ...            ...
1765  2018-01-01 23:41:11  read  country_2  2458153026   Reddit         Africa
1766  2018-01-01 23:41:51  read  country_5  2458153027  AdWords           Asia
1767  2018-01-01 23:43:54  read  country_5  2458153028  AdWords         Europe
1768  2018-01-01 23:44:52  read  country_8  2458153029   Reddit  South America
1769  2018-01-01 23:45:09  read  country_5  2458153030  AdWords      Australia
1770  2018-01-01 23:45:12  read  country_6  2458153031   Reddit           Asia
1771  2018-01-01 23:45:56  read  country_5  2458153032  AdWords         Africa
1772  2018-01-01 23:45:58  read  country_7  2458153033      SEO  South America
1773  2018-01-01 23:46:13  read  country_8  2458153034   Reddit           Asia
1774  2018-01-01 23:46:22  read  country_2  2458153035  AdWords           Asia
1775  2018-01-01 23:47:19  read  country_2  2458153036  AdWords           Asia
1776  2018-01-01 23:49:04  read  country_6  2458153037   Reddit           Asia
1777  2018-01-01 23:49:52  read  country_5  2458153038      SEO  North America
1778  2018-01-01 23:51:17  read  country_2  2458153039   Reddit           Asia
1779  2018-01-01 23:51:25  read  country_4  2458153040      SEO  South America
1780  2018-01-01 23:51:46  read  country_8  2458153041  AdWords         Africa
1781  2018-01-01 23:51:52  read  country_2  2458153042   Reddit           Asia
1782  2018-01-01 23:53:03  read  country_2  2458153043  AdWords           Asia
1783  2018-01-01 23:53:33  read  country_3  2458153044   Reddit           Asia
1784  2018-01-01 23:54:03  read  country_2  2458153045      SEO  North America
1785  2018-01-01 23:54:26  read  country_2  2458153046  AdWords         Africa
1786  2018-01-01 23:54:39  read  country_6  2458153047   Reddit           Asia
1787  2018-01-01 23:54:45  read  country_2  2458153048   Reddit           Asia
1788  2018-01-01 23:55:04  read  country_7  2458153049  AdWords         Europe
1789  2018-01-01 23:56:42  read  country_4  2458153050  AdWords           Asia
1790  2018-01-01 23:57:14  read  country_2  2458153051  AdWords  North America
1791  2018-01-01 23:58:33  read  country_8  2458153052      SEO           Asia
1792  2018-01-01 23:59:36  read  country_6  2458153053   Reddit           Asia
1793  2018-01-01 23:59:36  read  country_7  2458153054  AdWords         Europe
1794  2018-01-01 23:59:38  read  country_5  2458153055   Reddit           Asia

[1795 rows x 6 columns]

In [9]:
article_read.head()

           my_datetime event    country     user_id   source          topic
0  2018-01-01 00:01:01  read  country_7  2458151261      SEO  North America
1  2018-01-01 00:03:20  read  country_7  2458151262      SEO  South America
2  2018-01-01 00:04:01  read  country_7  2458151263  AdWords         Africa
3  2018-01-01 00:04:02  read  country_7  2458151264  AdWords         Europe
4  2018-01-01 00:05:03  read  country_8  2458151265   Reddit  North America

In [10]:
article_read.tail()

              my_datetime event    country     user_id   source          topic
1790  2018-01-01 23:57:14  read  country_2  2458153051  AdWords  North America
1791  2018-01-01 23:58:33  read  country_8  2458153052      SEO           Asia
1792  2018-01-01 23:59:36  read  country_6  2458153053   Reddit           Asia
1793  2018-01-01 23:59:36  read  country_7  2458153054  AdWords         Europe
1794  2018-01-01 23:59:38  read  country_5  2458153055   Reddit           Asia

In [11]:
article_read.sample(5)

              my_datetime event    country     user_id   source          topic
1620  2018-01-01 21:56:30  read  country_7  2458152881   Reddit  South America
600   2018-01-01 08:10:43  read  country_7  2458151861      SEO         Africa
275   2018-01-01 03:42:07  read  country_5  2458151536  AdWords         Europe
1722  2018-01-01 23:13:57  read  country_1  2458152983  AdWords         Europe
678   2018-01-01 09:19:47  read  country_2  2458151939  AdWords         Europe

In [12]:
article_read[['country', 'user_id']]

        country     user_id
0     country_7  2458151261
1     country_7  2458151262
2     country_7  2458151263
3     country_7  2458151264
4     country_8  2458151265
5     country_6  2458151266
6     country_2  2458151267
7     country_6  2458151268
8     country_7  2458151269
9     country_5  2458151270
10    country_5  2458151271
11    country_7  2458151272
12    country_5  2458151273
13    country_2  2458151274
14    country_7  2458151275
15    country_7  2458151276
16    country_8  2458151277
17    country_2  2458151278
18    country_4  2458151279
19    country_2  2458151280
20    country_2  2458151281
21    country_7  2458151282
22    country_2  2458151283
23    country_2  2458151284
24    country_7  2458151285
25    country_2  2458151286
26    country_5  2458151287
27    country_2  2458151288
28    country_2  2458151289
29    country_7  2458151290
...         ...         ...
1765  country_2  2458153026
1766  country_5  2458153027
1767  country_5  2458153028
1768  country_8  2458153029
1769  country_5  2458153030
1770  country_6  2458153031
1771  country_5  2458153032
1772  country_7  2458153033
1773  country_8  2458153034
1774  country_2  2458153035
1775  country_2  2458153036
1776  country_6  2458153037
1777  country_5  2458153038
1778  country_2  2458153039
1779  country_4  2458153040
1780  country_8  2458153041
1781  country_2  2458153042
1782  country_2  2458153043
1783  country_3  2458153044
1784  country_2  2458153045
1785  country_2  2458153046
1786  country_6  2458153047
1787  country_2  2458153048
1788  country_7  2458153049
1789  country_4  2458153050
1790  country_2  2458153051
1791  country_8  2458153052
1792  country_6  2458153053
1793  country_7  2458153054
1794  country_5  2458153055

[1795 rows x 2 columns]

In [13]:
article_read[['user_id', 'country']]

         user_id    country
0     2458151261  country_7
1     2458151262  country_7
2     2458151263  country_7
3     2458151264  country_7
4     2458151265  country_8
5     2458151266  country_6
6     2458151267  country_2
7     2458151268  country_6
8     2458151269  country_7
9     2458151270  country_5
10    2458151271  country_5
11    2458151272  country_7
12    2458151273  country_5
13    2458151274  country_2
14    2458151275  country_7
15    2458151276  country_7
16    2458151277  country_8
17    2458151278  country_2
18    2458151279  country_4
19    2458151280  country_2
20    2458151281  country_2
21    2458151282  country_7
22    2458151283  country_2
23    2458151284  country_2
24    2458151285  country_7
25    2458151286  country_2
26    2458151287  country_5
27    2458151288  country_2
28    2458151289  country_2
29    2458151290  country_7
...          ...        ...
1765  2458153026  country_2
1766  2458153027  country_5
1767  2458153028  country_5
1768  2458153029  country_8
1769  2458153030  country_5
1770  2458153031  country_6
1771  2458153032  country_5
1772  2458153033  country_7
1773  2458153034  country_8
1774  2458153035  country_2
1775  2458153036  country_2
1776  2458153037  country_6
1777  2458153038  country_5
1778  2458153039  country_2
1779  2458153040  country_4
1780  2458153041  country_8
1781  2458153042  country_2
1782  2458153043  country_2
1783  2458153044  country_3
1784  2458153045  country_2
1785  2458153046  country_2
1786  2458153047  country_6
1787  2458153048  country_2
1788  2458153049  country_7
1789  2458153050  country_4
1790  2458153051  country_2
1791  2458153052  country_8
1792  2458153053  country_6
1793  2458153054  country_7
1794  2458153055  country_5

[1795 rows x 2 columns]

In [17]:
article_read[article_read.topic == 'Australia']

              my_datetime event    country     user_id   source      topic
11    2018-01-01 00:08:57  read  country_7  2458151272      SEO  Australia
31    2018-01-01 00:26:28  read  country_7  2458151292   Reddit  Australia
33    2018-01-01 00:27:10  read  country_7  2458151294   Reddit  Australia
61    2018-01-01 00:55:48  read  country_7  2458151322  AdWords  Australia
63    2018-01-01 00:56:46  read  country_7  2458151324   Reddit  Australia
87    2018-01-01 01:18:12  read  country_6  2458151348      SEO  Australia
116   2018-01-01 01:42:15  read  country_2  2458151377   Reddit  Australia
153   2018-01-01 02:12:59  read  country_2  2458151414      SEO  Australia
159   2018-01-01 02:15:55  read  country_5  2458151420   Reddit  Australia
163   2018-01-01 02:19:48  read  country_7  2458151424   Reddit  Australia
188   2018-01-01 02:43:16  read  country_6  2458151449      SEO  Australia
190   2018-01-01 02:43:36  read  country_7  2458151451  AdWords  Australia
221   2018-01-01 03:08:43  read  country_2  2458151482  AdWords  Australia
223   2018-01-01 03:09:28  read  country_3  2458151484   Reddit  Australia
227   2018-01-01 03:10:36  read  country_6  2458151488  AdWords  Australia
238   2018-01-01 03:19:25  read  country_2  2458151499  AdWords  Australia
242   2018-01-01 03:22:56  read  country_6  2458151503  AdWords  Australia
297   2018-01-01 03:58:06  read  country_7  2458151558  AdWords  Australia
303   2018-01-01 04:07:19  read  country_2  2458151564   Reddit  Australia
338   2018-01-01 04:26:54  read  country_7  2458151599   Reddit  Australia
342   2018-01-01 04:28:30  read  country_2  2458151603   Reddit  Australia
343   2018-01-01 04:31:46  read  country_2  2458151604  AdWords  Australia
368   2018-01-01 04:56:29  read  country_4  2458151629   Reddit  Australia
378   2018-01-01 05:07:50  read  country_7  2458151639   Reddit  Australia
379   2018-01-01 05:10:22  read  country_5  2458151640   Reddit  Australia
413   2018-01-01 05:43:20  read  country_1  2458151674  AdWords  Australia
442   2018-01-01 06:02:34  read  country_2  2458151703   Reddit  Australia
451   2018-01-01 06:07:11  read  country_6  2458151712   Reddit  Australia
467   2018-01-01 06:18:57  read  country_6  2458151728  AdWords  Australia
498   2018-01-01 06:39:39  read  country_2  2458151759   Reddit  Australia
...                   ...   ...        ...         ...      ...        ...
1265  2018-01-01 17:05:48  read  country_8  2458152526   Reddit  Australia
1272  2018-01-01 17:12:00  read  country_6  2458152533   Reddit  Australia
1276  2018-01-01 17:15:39  read  country_7  2458152537   Reddit  Australia
1281  2018-01-01 17:17:53  read  country_5  2458152542   Reddit  Australia
1308  2018-01-01 17:44:35  read  country_8  2458152569      SEO  Australia
1349  2018-01-01 18:18:55  read  country_7  2458152610   Reddit  Australia
1368  2018-01-01 18:32:57  read  country_7  2458152629      SEO  Australia
1395  2018-01-01 18:58:51  read  country_5  2458152656   Reddit  Australia
1405  2018-01-01 19:07:24  read  country_2  2458152666   Reddit  Australia
1436  2018-01-01 19:31:02  read  country_2  2458152697   Reddit  Australia
1457  2018-01-01 19:50:41  read  country_2  2458152718   Reddit  Australia
1461  2018-01-01 19:53:21  read  country_8  2458152722  AdWords  Australia
1520  2018-01-01 20:41:06  read  country_5  2458152781  AdWords  Australia
1537  2018-01-01 20:52:37  read  country_5  2458152798   Reddit  Australia
1542  2018-01-01 20:54:41  read  country_7  2458152803   Reddit  Australia
1552  2018-01-01 21:00:46  read  country_2  2458152813  AdWords  Australia
1579  2018-01-01 21:24:11  read  country_6  2458152840   Reddit  Australia
1625  2018-01-01 21:59:52  read  country_5  2458152886  AdWords  Australia
1628  2018-01-01 22:03:53  read  country_5  2458152889  AdWords  Australia
1631  2018-01-01 22:04:28  read  country_2  2458152892   Reddit  Australia
1637  2018-01-01 22:07:57  read  country_2  2458152898      SEO  Australia
1669  2018-01-01 22:33:19  read  country_7  2458152930      SEO  Australia
1673  2018-01-01 22:40:42  read  country_6  2458152934   Reddit  Australia
1677  2018-01-01 22:43:43  read  country_7  2458152938   Reddit  Australia
1693  2018-01-01 22:53:13  read  country_2  2458152954  AdWords  Australia
1704  2018-01-01 22:59:53  read  country_2  2458152965   Reddit  Australia
1705  2018-01-01 23:00:20  read  country_5  2458152966   Reddit  Australia
1717  2018-01-01 23:08:49  read  country_7  2458152978  AdWords  Australia
1720  2018-01-01 23:11:49  read  country_2  2458152981   Reddit  Australia
1769  2018-01-01 23:45:09  read  country_5  2458153030  AdWords  Australia

[121 rows x 6 columns]

In [18]:
article_read.head()[['country', 'user_id']]

     country     user_id
0  country_7  2458151261
1  country_7  2458151262
2  country_7  2458151263
3  country_7  2458151264
4  country_8  2458151265

In [19]:
article_read[['country', 'user_id']].head()

     country     user_id
0  country_7  2458151261
1  country_7  2458151262
2  country_7  2458151263
3  country_7  2458151264
4  country_8  2458151265